stages:
  - build
  - test
  
docker:image:
  stage: build
  image: docker:1.11
  services:
    - docker:dind
  script:
    - export DOCKER_HOST=tcp://docker:2375/
    - docker version
    - docker build -t aimingds/dumbflix-ci:latest .
    # push only for tags
#    - "[[ -z $CI_BUILD_TAG ]] && exit 0"
#    - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker login -u aimingds -p $PASS_DOCKER
    - docker push aimingds/dumbflix-ci:latest

docker:deploy:
  stage: test
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $VM_ADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
  - ssh $SSH_USER@$VM_ADDRESS "cd ~/deploy/ && docker-compose up -d"
